# Site settings
title: Insafe (Inclusive and Safe Societies)
email: contact@rezaprama.com
description: > # this means to ignore newlines until "baseurl:"
  Insafe is awesome super app like gojek for housing property
baseurl: ""
url: "" # the base hostname & protocol for your site

# User setting
owner: Reza Prama Arviandi
email:
facebook_username:
twitter_username:
github_username: rezaprama
address:
  - line:
  - line:
  # Feel free to add more lines here 
telephone:
copyright:

# API settings
google_api_key:

# Build settings
markdown: kramdown
